<a href="https://colab.research.google.com/github/Naveensadanandan/Pytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.3.1+cu121'

In [2]:
#creating a scalar
scalar = torch.tensor(5)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(5)
0
5


In [3]:
#creating a vector
vector = torch.tensor([5,5])
print(vector)
print(vector.ndim)
print(vector.shape) #size and dim is different

tensor([5, 5])
1
torch.Size([2])


In [4]:
#Matrix

MATRIX = torch.tensor([[1,2],[2,3]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[1, 2],
        [2, 3]])
2
torch.Size([2, 2])


In [5]:
#tensor
tensor_3d = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]],[[7, 8, 92], [10, 112, 12]]])
print("3D Tensor:")
print(tensor_3d)

3D Tensor:
tensor([[[  1,   2,   3],
         [  4,   5,   6]],

        [[  7,   8,   9],
         [ 10,  11,  12]],

        [[  7,   8,  92],
         [ 10, 112,  12]]])


In [6]:
#selecting a specific element from tensor
tensor_3d[2,1,1]

tensor(112)

In [7]:
#creating random tensors
random_tensor = torch.rand(size = (1,4,4))
print(random_tensor.ndim, random_tensor.shape)


3 torch.Size([1, 4, 4])


In [8]:
#zeros and ones
print(torch.zeros(3,4))
print(torch.ones(3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [9]:
#Range in tensors

a = torch.arange(start=1, end=11, step=2)
b = torch.zeros_like(a)
print(a,b)

tensor([1, 3, 5, 7, 9]) tensor([0, 0, 0, 0, 0])


In [10]:
#dtypes in tensors
a.dtype

torch.int64

In [11]:
tensor_32 = torch.tensor([2.0,3.0,4.0])
tensor_32.dtype

torch.float32

In [12]:
tensor_16 = random_tensor.type(torch.float16)
tensor_16.dtype

torch.float16

In [13]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [14]:
torch.mul(tensor_32, float_32_tensor)

tensor([ 6., 18., 36.])

In [15]:
#Getting information from tensors using tensor attributes
some_tensor = torch.rand(3,4)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"device of tensor : {some_tensor.device}")
print(f"shape of tensor : {some_tensor.shape}")

Datatype of tensor : torch.float32
device of tensor : cpu
shape of tensor : torch.Size([3, 4])


In [16]:
#Manipulating tensors

tensor_1 = torch.tensor([[3,4],[5,6]])
tensor_2 = torch.tensor([[3,4],[3,8]])
print(tensor_1)
print(tensor_2)

tensor([[3, 4],
        [5, 6]])
tensor([[3, 4],
        [3, 8]])


In [17]:
#Addition and substraction
print(tensor_1 + 10)
print(tensor_1 - tensor_2)

tensor([[13, 14],
        [15, 16]])
tensor([[ 0,  0],
        [ 2, -2]])


In [18]:
#Multipication element wise
torch.mul(tensor_1, tensor_2)

tensor([[ 9, 16],
        [15, 48]])

In [19]:
#Matrix Mul
torch.matmul(tensor_1,tensor_2)

tensor([[21, 44],
        [33, 68]])

In [20]:
#Tensor aggregation
print(f"max : {torch.max(tensor_1)}")
print(f"min : {torch.min(tensor_1)}")
print(f"mean : {torch.mean(tensor_1.type(torch.float32))}") # since tensor mean is only supported in float and complex dtype

max : 6
min : 3
mean : 4.5


In [21]:
#position of max and min value
tensor_1 = torch.rand(4,4)
tensor_2 = torch.arange(0,21)
print(tensor_1)
print(tensor_2)
print(f"position of max in tensor_1 : {torch.argmax(tensor_1)}")
print(f"position of min in tensor_1 : {torch.argmin(tensor_1)}")
print(f"position of max in tensor_2 : {torch.argmax(tensor_2)}")
print(f"position of min in tensor_2 : {torch.argmin(tensor_2)}")


tensor([[0.6841, 0.2131, 0.2214, 0.8127],
        [0.9903, 0.0073, 0.4831, 0.0680],
        [0.0669, 0.7832, 0.2713, 0.0664],
        [0.9335, 0.0145, 0.7911, 0.0151]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20])
position of max in tensor_1 : 4
position of min in tensor_1 : 5
position of max in tensor_2 : 20
position of min in tensor_2 : 0


In [22]:
#Reshaping,stacking,squeezing
print(tensor_1)
print(tensor_1.reshape(8,2))
print(torch.stack([tensor_1,tensor_1], dim = 0)) #dim = 1or0

tensor([[0.6841, 0.2131, 0.2214, 0.8127],
        [0.9903, 0.0073, 0.4831, 0.0680],
        [0.0669, 0.7832, 0.2713, 0.0664],
        [0.9335, 0.0145, 0.7911, 0.0151]])
tensor([[0.6841, 0.2131],
        [0.2214, 0.8127],
        [0.9903, 0.0073],
        [0.4831, 0.0680],
        [0.0669, 0.7832],
        [0.2713, 0.0664],
        [0.9335, 0.0145],
        [0.7911, 0.0151]])
tensor([[[0.6841, 0.2131, 0.2214, 0.8127],
         [0.9903, 0.0073, 0.4831, 0.0680],
         [0.0669, 0.7832, 0.2713, 0.0664],
         [0.9335, 0.0145, 0.7911, 0.0151]],

        [[0.6841, 0.2131, 0.2214, 0.8127],
         [0.9903, 0.0073, 0.4831, 0.0680],
         [0.0669, 0.7832, 0.2713, 0.0664],
         [0.9335, 0.0145, 0.7911, 0.0151]]])


In [23]:
x = torch.zeros(2,1,2,1,2)
y = torch.squeeze(x) #Squeezes input to remove all the dimenions with value 1.
print(f"previous shape : {x.shape}")
print(f"new shape : {y.shape}")

previous shape : torch.Size([2, 1, 2, 1, 2])
new shape : torch.Size([2, 2, 2])


In [24]:
x = torch.zeros(2,2,2)
y = torch.unsqueeze(x,0) #Returns input with a dimension value of 1 added at dim.
print(f"previous shape : {x.shape}")
print(f"new shape : {y.shape}")

previous shape : torch.Size([2, 2, 2])
new shape : torch.Size([1, 2, 2, 2])


In [28]:
#torch.permute rearrange the dimension of a tensor in a specific order

tensor = torch.rand(size = (224,224,3))
tensor_permuted = torch.permute(tensor,(2, 0, 1))
print(f"The size of permuted tensor is {tensor_permuted.shape}")

The size of permuted tensor is torch.Size([3, 224, 224])


In [29]:
#changing a element in tensor
print(tensor[1,1,1])
tensor[1,1,1] = 0.5
tensor[1,1,1]

tensor(0.8410)


tensor(0.5000)

In [32]:
#Indexing
tensor = torch.arange(1, 10).reshape(shape = (1, 3, 3))
tensor, tensor.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [41]:
 #select only first element
print(f"first element : {tensor[0][0][0]}")
print(f"second element : {tensor[0][0][1]}")
print(f"first row : {tensor[0][0][:]}")
print(f"secong column : {tensor[0,:,1]}")

first element : 1
second element : 2
first row : tensor([1, 2, 3])
secong column : tensor([2, 5, 8])


In [2]:
#pytorch tensor to numpy
import torch
import numpy as np
tensor = torch.arange(1.0,10.0)
array = tensor.numpy()
print(tensor)
print(array)
print(f"data type of numpy array is {array.dtype}")

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
data type of numpy array is float32


In [6]:
array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array)
tensor_32 = tensor.type(torch.float32)
print(array)
print(tensor)
print(f"data type of tensor is {tensor.dtype}")
print(f"data type of tensor_32 is {tensor_32.dtype}")
#tensor defualt datatype is float32 but convertion cause it to be float 64 until specified

[1. 2. 3. 4. 5. 6. 7. 8. 9.]
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
data type of tensor is torch.float64
data type of tensor_32 is torch.float32


In [8]:
#Reproducing tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
torch.rand(3,4) # if you run this cell even multiple times we will get same random numbers

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [5]:
#tensor to gpu
tensor = torch.tensor([1,23,3])
print(tensor, tensor.device)

tensor_gpu = tensor.to(device)
print(tensor_gpu, tensor_gpu.device)


tensor([ 1, 23,  3]) cpu
tensor([ 1, 23,  3], device='cuda:0') cuda:0


In [7]:
#tensor back to cpu
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [8]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_gpu.cpu().numpy()
tensor_back_on_cpu

array([ 1, 23,  3])