<a href="https://colab.research.google.com/github/Naveensadanandan/Pytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
torch.__version__

'2.3.1+cu121'

In [ ]:
#creating a scalar
scalar = torch.tensor(5)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(5)
0
5


In [ ]:
#creating a vector
vector = torch.tensor([5,5])
print(vector)
print(vector.ndim)
print(vector.shape) #size and dim is different

tensor([5, 5])
1
torch.Size([2])


In [ ]:
#Matrix

MATRIX = torch.tensor([[1,2],[2,3]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[1, 2],
        [2, 3]])
2
torch.Size([2, 2])


In [ ]:
#tensor
tensor_3d = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]],[[7, 8, 92], [10, 112, 12]]])
print("3D Tensor:")
print(tensor_3d)

3D Tensor:
tensor([[[  1,   2,   3],
         [  4,   5,   6]],

        [[  7,   8,   9],
         [ 10,  11,  12]],

        [[  7,   8,  92],
         [ 10, 112,  12]]])


In [ ]:
#selecting a specific element from tensor
tensor_3d[2,1,1]

tensor(112)

In [ ]:
#creating random tensors
random_tensor = torch.rand(size = (1,4,4))
print(random_tensor.ndim, random_tensor.shape)


3 torch.Size([1, 4, 4])


In [ ]:
#zeros and ones
print(torch.zeros(3,4))
print(torch.ones(3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [ ]:
#Range in tensors

a = torch.arange(start=1, end=11, step=2)
b = torch.zeros_like(a)
print(a,b)

tensor([1, 3, 5, 7, 9]) tensor([0, 0, 0, 0, 0])


In [ ]:
#dtypes in tensors
a.dtype

torch.int64

In [ ]:
tensor_32 = torch.tensor([2.0,3.0,4.0])
tensor_32.dtype

torch.float32

In [ ]:
tensor_16 = random_tensor.type(torch.float16)
tensor_16.dtype

torch.float16

In [ ]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [ ]:
torch.mul(tensor_32, float_32_tensor)

tensor([ 6., 18., 36.])

In [ ]:
#Getting information from tensors using tensor attributes
some_tensor = torch.rand(3,4)
print(f"Datatype of tensor : {some_tensor.dtype}")
print(f"device of tensor : {some_tensor.device}")
print(f"shape of tensor : {some_tensor.shape}")

Datatype of tensor : torch.float32
device of tensor : cpu
shape of tensor : torch.Size([3, 4])


In [ ]:
#Manipulating tensors

tensor_1 = torch.tensor([[3,4],[5,6]])
tensor_2 = torch.tensor([[3,4],[3,8]])
print(tensor_1)
print(tensor_2)

tensor([[3, 4],
        [5, 6]])
tensor([[3, 4],
        [3, 8]])


In [ ]:
#Addition and substraction
print(tensor_1 + 10)
print(tensor_1 - tensor_2)

tensor([[13, 14],
        [15, 16]])
tensor([[ 0,  0],
        [ 2, -2]])


In [ ]:
#Multipication element wise
torch.mul(tensor_1, tensor_2)

tensor([[ 9, 16],
        [15, 48]])

In [ ]:
#Matrix Mul
torch.matmul(tensor_1,tensor_2)

tensor([[21, 44],
        [33, 68]])

In [ ]:
#Tensor aggregation
print(f"max : {torch.max(tensor_1)}")
print(f"min : {torch.min(tensor_1)}")
print(f"mean : {torch.mean(tensor_1.type(torch.float32))}") # since tensor mean is only supported in float and complex dtype

max : 6
min : 3
mean : 4.5


In [ ]:
#position of max and min value
tensor_1 = torch.rand(4,4)
tensor_2 = torch.arange(0,21)
print(tensor_1)
print(tensor_2)
print(f"position of max in tensor_1 : {torch.argmax(tensor_1)}")
print(f"position of min in tensor_1 : {torch.argmin(tensor_1)}")
print(f"position of max in tensor_2 : {torch.argmax(tensor_2)}")
print(f"position of min in tensor_2 : {torch.argmin(tensor_2)}")


tensor([[0.2492, 0.8697, 0.1770, 0.9031],
        [0.0536, 0.4586, 0.8182, 0.6189],
        [0.8126, 0.9297, 0.6570, 0.5710],
        [0.2513, 0.3423, 0.3751, 0.5748]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20])
position of max in tensor_1 : 9
position of min in tensor_1 : 4
position of max in tensor_2 : 20
position of min in tensor_2 : 0


In [ ]:
#Reshaping,stacking,squeezing
print(tensor_1)
print(tensor_1.reshape(8,2))
print(torch.stack([tensor_1,tensor_1], dim = 0)) #dim = 1or0

tensor([[0.2492, 0.8697, 0.1770, 0.9031],
        [0.0536, 0.4586, 0.8182, 0.6189],
        [0.8126, 0.9297, 0.6570, 0.5710],
        [0.2513, 0.3423, 0.3751, 0.5748]])
tensor([[0.2492, 0.8697],
        [0.1770, 0.9031],
        [0.0536, 0.4586],
        [0.8182, 0.6189],
        [0.8126, 0.9297],
        [0.6570, 0.5710],
        [0.2513, 0.3423],
        [0.3751, 0.5748]])
tensor([[[0.2492, 0.8697, 0.1770, 0.9031],
         [0.0536, 0.4586, 0.8182, 0.6189],
         [0.8126, 0.9297, 0.6570, 0.5710],
         [0.2513, 0.3423, 0.3751, 0.5748]],

        [[0.2492, 0.8697, 0.1770, 0.9031],
         [0.0536, 0.4586, 0.8182, 0.6189],
         [0.8126, 0.9297, 0.6570, 0.5710],
         [0.2513, 0.3423, 0.3751, 0.5748]]])


In [ ]:
x = torch.zeros(2,1,2,1,2)
y = torch.squeeze(x) #Squeezes input to remove all the dimenions with value 1.
print(f"previous shape : {x.shape}")
print(f"new shape : {y.shape}")

previous shape : torch.Size([2, 1, 2, 1, 2])
new shape : torch.Size([2, 2, 2])


In [ ]:
x = torch.zeros(2,2,2)
y = torch.unsqueeze(x,0) #Returns input with a dimension value of 1 added at dim.
print(f"previous shape : {x.shape}")
print(f"new shape : {y.shape}")

previous shape : torch.Size([2, 2, 2])
new shape : torch.Size([1, 2, 2, 2])
