<a href="https://colab.research.google.com/github/Naveensadanandan/Pytorch/blob/main/pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
torch.__version__

'2.3.1+cu121'

In [5]:
#creating a scalar
scalar = torch.tensor(5)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(5)
0
5


In [4]:
#creating a vector
vector = torch.tensor([5,5])
print(vector)
print(vector.ndim)
print(vector.shape) #size and dim is different

tensor([5, 5])
1
torch.Size([2])


In [6]:
#Matrix

MATRIX = torch.tensor([[1,2],[2,3]])
print(MATRIX)
print(MATRIX.ndim)
print(MATRIX.shape)

tensor([[1, 2],
        [2, 3]])
2
torch.Size([2, 2])


In [7]:
#tensor
tensor_3d = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("3D Tensor:")
print(tensor_3d)

3D Tensor:
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
